[basic_settings]
src = "/etc/lbecm/config.ini"
name = "lbecm"
[etcd]
hosts = "PUBLIC"
[grpc]
port = "PUBLIC"
[cluster]
# name of the region where the node is located
zone = "PRIVATE"
# node host
host = "PRIVATE"
