[basic_settings]
src = "/etc/lbecm/config.ini"

[etcd]
hosts = _NEEDSYNC_
retry_times = 5
[grpc]
# grpc port for weight
port = _NEEDSYNC_
# grpc timeout
timeout = 2000
# grpc workers count
max_workers = 10
[cluster]
# name of the region where the node is located
zone = _NEEDSYNC_
# node host
host = _NEEDSYNC_
# It's useless, just set to true
is_master = true
# pools = .rgw.buckets.data.standard,.rgw.buckets.data.ia
pools = .rgw.buckets.data.standard,.rgw.bucket.data.ia
# 
thresholds = 0.8
#
max_conn = 30000
[ecm]
# 保活租约时长(秒) 一般不用动
ttl = 20
# Interval time(minute)
wait_time = 1
# log level
log_level = INFO
# compressed size
rotation = 20 MB
# Check cycle of data difference between ceph and etcd
check_time = 2
